version: '3.8'

services:
  csv-app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: csv-management-app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MAX_FILE_SIZE=10485760  # 10MB in bytes
      - CORS_ORIGINS=*
    volumes:
      # Temporary file storage (cleared on restart)
      - uploads:/app/backend/uploads
      - temp:/app/backend/temp
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - csv-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: csv-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - csv-app
    networks:
      - csv-network
    profiles:
      - production

volumes:
  uploads:
    driver: local
  temp:
    driver: local

networks:
  csv-network:
    driver: bridge